name: Daily Data Fetch (RTWH)

on:
  schedule:
    - cron: '23 11 * * *' # daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright (Chromium)
        run: |
          if [ ! -f package.json ]; then npm init -y; fi
          npm i -D playwright
          npx playwright install --with-deps chromium

      - name: Fetch RTWH poll data
        run: node fetch-data.js

      - name: Save changes
        run: |
          git config user.name "Bot"
          git config user.email "bot@users.noreply.github.com"
          git add polls.json rtwh_sources.json
          git commit -m "Update poll data (RTWH)" || exit 0
          git push
